---
services:
  ub2:
    image: riaktr/ub2:1.4.0
    command: --configfile=/deploy/ub2-daemonized.toml
    restart: 'always'
    environment:
      COMPOSE_HTTP_TIMEOUT: 360
    read_only: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /root/.docker
        target: /root/.docker
        read_only: true
      - type: bind
        source: /RIA/__DELIVERY_REPOSITORY_NAME__
        target: /deploy
        read_only: false
      - type: volume
        source: config-store
        target: /data
        read_only: false
      - type: volume
        source: seeds
        target: /seeds
        read_only: false

volumes:
  config-store: {}
  seeds: {}

networks:
  default:
    name: ria
