# Top level configuration
########################################################################################################
# Whether to deploy using docker-compose or docker swarm
# accepted valuse are "compose" or "swarm"
# when using Swarm, make sure that you are running the deployment on the manager node
DeploymentMode = "compose"

# Set the deployer in debug mode
Debug = false

# Unique identifier for the deployment (e.g. for Slack integration)
DeploymentID = "GROUP-OPCO-ENV"

# Whether or not to force pull images from DockerHub
PullDockerImages = true

# Whether or not to pull changes from GitHub
PullGit = true

# Pull interval for GitHub (in seconds)
PullInterval = 300

# Whether to deploy continuously (aka in deamon mode) or once
Daemonize = true

########################################################################################################
# Feature flags for deployment steps
########################################################################################################
[DeploymentFeatureFlagsConfig]
# Whether or not to seed configuration in Consul
SeedConsul = true
# Whether or not to provision Keycloak authentication system (realm, roles, groups)
SeedKeycloak = false
# Whether or not to provision user accounts and restrictions
SeedUsers = false
# Whether or not to skip `docker-compose up`
SkipDeployment = false
# Whether or not to skip the seeding of the data (e.g. SQL, Minio)
SkipDataSeeds = true

########################################################################################################
# Consul configuration
########################################################################################################
[ConsulConfig]
# Override the Consul token used to seed the KV store
#ACLToken = ""

########################################################################################################
# Data seed configuration
########################################################################################################
[DataSeedConfig]
# Override the list of containers that we wait before seeding
#WaitForHealthCheckList = ["data-broker-service-db"]

########################################################################################################
# Whitelist of stacks to deploy
########################################################################################################
[ComponentsStacksConfig]
# Define the list of Compose files to deploy based on the folder structure
# For instance:
#   ./deployment/stack1/docker-compose.yml
#   ./deployment/stack2/docker-compose.yml
#   ./deployment/stack3/docker-compose.yml
# StacksList = [stack2] will only deploy stack2
# StacksList = [stack1, stack3] will only deploy stack1 and stack3
StacksList = []

########################################################################################################
# Keycloak configuration
########################################################################################################
[KeycloakConfig]
# Wheter or not to delete and fully recreate the realm
ForceRecreateFullRealm = false

########################################################################################################
# Data restrictions configuration
########################################################################################################
[DataRestrictionsConfig]
# 2 policies are available:
# - "lenient": no entry in the whitelist means that the user can access everything (default)
# - "strict": no entry in the whitelist means that the user cannot access anything
DefaultPolicy = "lenient"

########################################################################################################
# Users provisioning configuration
########################################################################################################
[UsersProvisioningConfig]
# Only taken into account if SeedUsers is set to true
CreateKeycloakAccounts = true
SetDataRestrictions = true

# Set or reset user credentials from file user-credentials.csv (that file is NOT intended to be tracked in git)
# 3 strategies are available:
# - "no": do nothing (default)
# - "temporary": set the passwords defined in the file user-credentials.csv as temporary passwords
# - "permanent": set the passwords defined in the file user-credentials.csv as permanent passwords
SetCredentials = "temporary"

########################################################################################################
# Github configuration
########################################################################################################
[GitConfig]
Branch = "dev-server"
DeployKeyLocation = "/deploy/secrets/github_deploy_key/git-deploy-key"
Repository = "__DELIVERY_REPOSITORY_NAME__"
